name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2d1c1198e79c30cca5c3957b1e3b65ce95b5356e
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@76d3665dc084409ba9e6c467009338cf86e9dd5f
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}